### ISSUE TITLE
App Name change to wedialog

### ISSUE THREAD

**Issue by pieterharo** [CysionLiu/WeDialog#1]
Why all my app name, and my toolbar change to wedialog, and cant change it

**Comment by CysionLiu** [comment]
You have set the same app_name in strings.xml in some module,I think you should set your app_name in you application module.

**Comment by pieterharo** [comment]
all my toolbar and app name change after using wedialog, i dont change anything, and dont change anything in AndroidManifest

**Comment by pieterharo** [comment]
i've try hardcode my app label, and still "wedialog"
