### ISSUE TITLE
ERROR: Failed to resolve: com.cysion:WeDialog:1.1.0.x

### ISSUE THREAD

**Issue by darthcow** [CysionLiu/WeDialog#2]
seems Gradle cant find your lib even though I've added jcenter() to the repositories on project level .gradle. Any help?

**Comment by CysionLiu** [comment]
there was an error when upload v-1.1.0.x  to jcenter.  use 1.0.5.x instead. 1.1.0.x will work in few days

**Comment by CysionLiu** [comment]
use 1.2.0.x

**Comment by darthcow** [comment]
Thank you, today the version 1.1.0.x  worked.  the 1.2.0.x version is the latest?
